In [6]:
import numpy as np
import math

In [17]:
mat1 = np.array([[1,2,3],
                 [3,4,4],
                [5,6,7]])
mat2 = np.array([[5,6,1],
                 [7,8,2],
                [9,5,4]])

print("Matrix Multiplication: ", mat1 @ mat2,sep="\n")

det = np.linalg.det(mat1)
print("Determinant: ",det)

if det==0:
    print("Inverse not possible")
else:
    inv_mat = np.linalg.inv(mat1)
    print("Inverse",inv_mat,sep="\n")
print()
if(det != 0):
    i_mat = mat1 @ inv_mat
    print(i_mat)

Matrix Multiplication: 
[[ 46  37  17]
 [ 79  70  27]
 [130 113  45]]
Determinant:  -3.9999999999999973
Inverse
[[-1.   -1.    1.  ]
 [ 0.25  2.   -1.25]
 [ 0.5  -1.    0.5 ]]

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.66133815e-16  1.00000000e+00 -4.44089210e-16]
 [ 8.32667268e-16  4.44089210e-16  1.00000000e+00]]


In [23]:
marks = [10,20,30,40,50,60,70,80,90,100]
arr = np.array(marks)
mean = np.mean(arr)
print("Average:",mean)
for i in marks:
    if i > mean:
        print(i)

Average: 55.0
60
70
80
90
100
