In [2]:
import numpy as np

In [6]:
arr = np.array(["Amlan","ITER","2G3"])

In [8]:
print(arr[0],arr[1],arr[2])

Amlan ITER 2G3


In [10]:
two_d_arr = np.array([[2,3],
                    [4,5]])

In [15]:
for i in range(0,len(two_d_arr)):
    for j in range(0,len(two_d_arr)):
        print(two_d_arr[i][j],end = " ")
    print()

2 3 
4 5 


### Slicing

In [51]:
a = np.array([1,2,3,4])
print(a[0])#first element
print(a[1])#last element
print(a[1:4])#slicing

1
2
[2 3 4]


In [26]:
### Create a 2D array of dimension 3x3.
### print the element in row 2 column 1
### print all rows in 3rd column
### print 2nd row all columns


b = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(b[1,0])
print(b[:,2])
print(b[1,:])

4
[3 6 9]
[4 5 6]


In [32]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print("Sum:",x+y)
print("Product:",x*y)
print("Square of x:",x**2)
print("Square root of x:",np.sqrt(x))
print("Exponentiation:",np.exp(x))
print("Sin of x:",np.sin(x))

Sum: [5 7 9]
Product: [ 4 10 18]
Square of x: [1 4 9]
Square root of x: [1.         1.41421356 1.73205081]
Exponentiation: [ 2.71828183  7.3890561  20.08553692]
Sin of x: [0.84147098 0.90929743 0.14112001]


### Create 2*2 matrix do multiplicatin,dot product and tranpose

In [36]:

m1 = np.array([[1,2],
               [3,4]])
m2 = np.array([[5,6],
               [7,8]])
print(m1 @ m2)#matrix multiplication
print(np.dot(m1,m2))#dot product
print(m1.T)#Transpose

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


### sum,mean,max,min an std of 1D matrix

In [39]:
nums = np.array([1,2,3,4,5])
print(nums.sum())
print(nums.mean())
print(nums.max())
print(nums.min())
print(nums.std())

15
3.0
5
1
1.4142135623730951


### Arange Function

In [43]:
arr = np.arange(1,13)

reshaped = arr.reshape(3,4)
print(reshaped)

flattened = reshaped.flatten()
print(flattened)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### Random

In [48]:
print(np.random.rand(3))        #Three random numbers
print(np.random.randint(1,10,5))#5 random numbers of int type in range from [1,10)
print(np.random.rand(2,3))      #float matrix of 2x3

[0.56595336 0.22669767 0.55219901]
[9 8 3 5 2]
[[0.91592435 0.48852979 0.94167399]
 [0.77902952 0.90233082 0.82619124]]


In [50]:
arr_float = arr.astype(float)
print(arr_float)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
